In [1]:
# Import the libraries needed
import pandas as pd
import numpy as np
import re
import calendar

In [3]:
# Load the data into a pandas dataframe. 
# The steps for generating this dataset is described in the Build-Tableau-Dashboard.ipynb notebook
movies_cleaned = pd.read_csv("data/movies_cleaned.csv")
movies_cleaned.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,overview,...,release_year,budget_adj,revenue_adj,based_on_novel,release_month,release_day,release_dayofweek,profit,profit (%),profit_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,Twenty-two years after the events of Jurassic ...,...,2015,1.379999e+08,1.392446e+09,False,Jun,9,Tuesday,1363528810,909.019207,1.254446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,An apocalyptic story set in the furthest reach...,...,2015,1.379999e+08,3.481613e+08,False,May,13,Wednesday,228436354,152.290903,2.101614e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,Beatrice Prior must confront her inner demons ...,...,2015,1.012000e+08,2.716190e+08,True,Mar,18,Wednesday,185238201,168.398365,1.704191e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Thirty years after defeating the Galactic Empi...,...,2015,1.839999e+08,1.902723e+09,False,Dec,15,Tuesday,1868178225,934.089113,1.718723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Deckard Shaw seeks revenge against Dominic Tor...,...,2015,1.747999e+08,1.385749e+09,False,Apr,1,Wednesday,1316249360,692.762821,1.210949e+09

In [4]:
movies_cleaned.dtypes

id                        int64
imdb_id                  object
popularity              float64
budget                    int64
revenue                   int64
original_title           object
cast                     object
homepage                 object
director                 object
overview                 object
runtime                   int64
genres                   object
production_companies     object
release_date             object
vote_count                int64
vote_average            float64
release_year              int64
budget_adj              float64
revenue_adj             float64
based_on_novel           object
release_month            object
release_day               int64
release_dayofweek        object
profit                    int64
profit (%)              float64
profit_adj              float64
dtype: object

Find proportion of movies that have `vote_average` > average `vote_average` and `profit_adj` > average profit_adj for each category - `based_on_novel` True and False. I call this quadrant magic quadrant.

In [6]:
magic_quadrant = (movies_cleaned["based_on_novel"][(movies_cleaned["vote_average"] > 5.947) & 
        (movies_cleaned["profit_adj"] > 41937684)].value_counts())/(movies_cleaned["based_on_novel"].value_counts())
magic_quadrant

False    0.173082
True     0.296154
Name: based_on_novel, dtype: float64